import React from 'react';
import { motion } from 'framer-motion';
import { 
  RadialBarChart, RadialBar, Legend, ResponsiveContainer, Tooltip, 
  BarChart, Bar, XAxis, YAxis, CartesianGrid
} from 'recharts';
import { InterviewReport } from '@/types';
import { CheckCircle2, AlertTriangle, TrendingUp, Award, Share2, Home } from 'lucide-react';

interface ReportDashboardProps {
  report: InterviewReport;
  onReset: () => void;
}

const ReportDashboard: React.FC<ReportDashboardProps> = ({ report, onReset }) => {
  
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { 
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1 }
  };

  // Prepare data for Radial Chart
  const scoreData = [
    { name: 'Overall', uv: report.overallScore, fill: '#6366f1' }, // indigo-500
    { name: 'Technical', uv: report.technicalScore, fill: '#8b5cf6' }, // violet-500
    { name: 'Comm.', uv: report.communicationScore, fill: '#ec4899' }, // pink-500
    { name: 'Culture', uv: report.cultureFitScore, fill: '#06b6d4' }, // cyan-500
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8 overflow-y-auto w-full">
      <div className="max-w-7xl mx-auto">
        
        {/* Header */}
        <header className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-display font-bold text-white mb-1">Performance Report</h1>
            <p className="text-slate-400 text-sm">Generated by Nexus AI • {new Date().toLocaleDateString()}</p>
          </div>
          <div className="flex gap-3">
             <button onClick={onReset} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 transition-colors text-sm">
                <Home size={16} /> Dashboard
             </button>
             <button className="flex items-center gap-2 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-colors text-sm font-medium">
                <Share2 size={16} /> Share
             </button>
          </div>
        </header>

        {/* Bento Grid */}
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="grid grid-cols-1 md:grid-cols-4 lg:grid-cols-4 gap-4 md:gap-6 auto-rows-[minmax(180px,auto)]"
        >
          
          {/* Main Score Card (Large) */}
          <motion.div variants={itemVariants} className="md:col-span-2 md:row-span-2 bg-white/5 backdrop-blur-sm border border-white/5 rounded-2xl p-6 relative overflow-hidden group">
             <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity">
                <Award size={120} />
             </div>
             <h2 className="text-lg font-semibold text-slate-300 mb-4">Overall Competency</h2>
             <div className="flex items-center justify-center h-[80%]">
                <div className="relative w-full h-full min-h-[250px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <RadialBarChart cx="50%" cy="50%" innerRadius="10%" outerRadius="100%" barSize={20} data={scoreData}>
                      <RadialBar
                        label={{ position: 'insideStart', fill: '#fff' }}
                        background
                        dataKey="uv"
                      />
                      <Legend iconSize={10} layout="vertical" verticalAlign="middle" wrapperStyle={{ right: 0 }} />
                      <Tooltip 
                        contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: '8px' }}
                        itemStyle={{ color: '#fff' }}
                      />
                    </RadialBarChart>
                  </ResponsiveContainer>
                  {/* Centered Score Text */}
                  <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                     <div className="text-center mt-4">
                        <span className="text-5xl font-bold font-display text-white">{report.overallScore}</span>
                        <span className="text-slate-400 text-sm block">/100</span>
                     </div>
                  </div>
                </div>
             </div>
          </motion.div>

          {/* Feedback Summary (Tall) */}
          <motion.div variants={itemVariants} className="md:col-span-2 md:row-span-1 bg-white/5 backdrop-blur-sm border border-white/5 rounded-2xl p-6">
             <h2 className="text-lg font-semibold text-slate-300 mb-2">Executive Summary</h2>
             <p className="text-slate-400 leading-relaxed text-sm">
               {report.summary}
             </p>
          </motion.div>

          {/* Strengths (Standard) */}
          <motion.div variants={itemVariants} className="md:col-span-2 bg-white/5 backdrop-blur-sm border border-white/5 rounded-2xl p-6 border-l-4 border-l-green-500/50">
             <div className="flex items-center gap-2 mb-4">
                <CheckCircle2 className="text-green-400" size={20} />
                <h3 className="font-semibold text-white">Key Strengths</h3>
             </div>
             <ul className="space-y-3">
               {report.feedback.filter(f => f.type === 'strength').map((item, idx) => (
                 <li key={idx} className="bg-white/5 rounded-lg p-3">
                    <p className="text-sm font-medium text-green-300">{item.title}</p>
                    <p className="text-xs text-slate-400 mt-1">{item.description}</p>
                 </li>
               ))}
             </ul>
          </motion.div>

          {/* Improvements (Standard) */}
          <motion.div variants={itemVariants} className="md:col-span-2 bg-white/5 backdrop-blur-sm border border-white/5 rounded-2xl p-6 border-l-4 border-l-orange-500/50">
             <div className="flex items-center gap-2 mb-4">
                <AlertTriangle className="text-orange-400" size={20} />
                <h3 className="font-semibold text-white">Areas for Improvement</h3>
             </div>
             <ul className="space-y-3">
               {report.feedback.filter(f => f.type === 'improvement').map((item, idx) => (
                 <li key={idx} className="bg-white/5 rounded-lg p-3">
                    <p className="text-sm font-medium text-orange-300">{item.title}</p>
                    <p className="text-xs text-slate-400 mt-1">{item.description}</p>
                 </li>
               ))}
             </ul>
          </motion.div>

          {/* Detailed Metrics Bar Chart (Wide) */}
          <motion.div variants={itemVariants} className="md:col-span-4 bg-white/5 backdrop-blur-sm border border-white/5 rounded-2xl p-6 h-[300px]">
             <h2 className="text-lg font-semibold text-slate-300 mb-4 flex items-center gap-2">
               <TrendingUp size={18} /> Detailed Radar Metrics
             </h2>
             <ResponsiveContainer width="100%" height="100%">
               <BarChart data={report.radarData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                  <XAxis dataKey="category" stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                  <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                  <Tooltip 
                     cursor={{ fill: 'rgba(255,255,255,0.05)' }}
                     contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155' }}
                  />
                  <Bar dataKey="score" fill="#818cf8" radius={[4, 4, 0, 0]} barSize={40} />
               </BarChart>
             </ResponsiveContainer>
          </motion.div>

        </motion.div>
      </div>
    </div>
  );
};

export default ReportDashboard;
